# Generated by Django 5.1.2 on 2024-10-12 11:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('slug', models.CharField(max_length=50, verbose_name='اسلاگ')),
                ('publish', models.DateTimeField(default=datetime.datetime(2024, 10, 12, 11, 34, 1, 499706, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DF', max_length=2, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'ordering': ['publish'],
                'indexes': [models.Index(fields=['publish'], name='sabzwebapp__publish_0f41d6_idx')],
            },
        ),
    ]
