# Generated by Django 5.1.2 on 2024-10-13 13:00

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabzwebapp', '0003_alter_post_created_alter_post_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 10, 13, 13, 0, 33, 436962, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار'),
        ),
    ]
