# Generated by Django 5.1.2 on 2024-10-14 12:50

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabzwebapp', '0008_alter_post_publish_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sabzwebapp.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 10, 14, 12, 50, 18, 13641, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار'),
        ),
    ]
