# Generated by Django 5.1.2 on 2024-10-14 12:51

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabzwebapp', '0009_alter_comment_post_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2024, 10, 14, 12, 51, 9, 725917, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انتشار'),
        ),
    ]
