# Generated by Django 5.1.2 on 2024-10-19 19:04

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabzwebapp', '0015_account_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('تکنولوژی', 'تکنولوژی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('برنامه نویسی', 'برنامه نویسی'), ('سایر', 'سایر')], default='سایر', null=True, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
